# Generated by Django 5.2.15 on 2026-06-13 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='occasioncategory',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AlterModelOptions(
            name='saree',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={},
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='device_info',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_source',
            field=models.CharField(choices=[('website', 'Website'), ('video_shopping', 'Video Shopping'), ('live_show', 'Live Show'), ('whatsapp', 'WhatsApp'), ('phone', 'Phone'), ('other', 'Other')], default='website', max_length=40),
        ),
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='address',
            name='landmark',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='saree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.saree'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='selected_color',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='selected_size',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('upi', 'UPI'), ('card', 'Card'), ('netbanking', 'Net Banking'), ('wallet', 'Wallet'), ('other', 'Other')], default='cod', max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=24),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='saree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.saree'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='selected_color',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='selected_size',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saree',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.sareecategory'),
        ),
        migrations.AlterField(
            model_name='saree',
            name='colors',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='saree',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='saree',
            name='images',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='saree',
            name='information',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='saree',
            name='name_ta',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AlterField(
            model_name='saree',
            name='occasion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.occasioncategory'),
        ),
        migrations.AlterField(
            model_name='saree',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='saree',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='saree',
            name='saree_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='saree',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='saree',
            name='video_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sareecategory',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='sareecategory',
            name='name_ta',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='saree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.saree'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('saree', 'user')},
        ),
        migrations.CreateModel(
            name='VideoShoppingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=5)),
                ('note', models.TextField(blank=True)),
                ('meet_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
            ],
            options={
                'ordering': ['date', 'time_slot'],
                'unique_together': {('date', 'time_slot')},
            },
        ),
        migrations.CreateModel(
            name='VideoShoppingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('slot_date', models.DateField()),
                ('slot_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=24)),
                ('meet_link', models.URLField(blank=True, default='', max_length=300)),
                ('notes', models.TextField(blank=True, default='')),
                ('email_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slot_date', 'slot_time'],
                'unique_together': {('slot_date', 'slot_time')},
            },
        ),
    ]
