# Generated by Django 5.0.6 on 2026-06-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_address_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoshoppingbooking',
            name='attendee_name',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='videoshoppingbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
